### ISSUE TITLE
Only works with X11, or XWayland Apps

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [lestcape/Gnome-Global-AppMenu#28] opened 2017-05-09 02:36 UTC
I do not know why, but for some reason, only non gtk3 apps running in XWayland, like Google Chrome, export their menus to this extension. many other apps which support the same, like Totem, or Gnome Terminal, only do so in GNOME on X11. in GNOME on Wayland, the extension doesn't even **know** the new app opened, as it displays the name and menus of the last used X11 app. 

examples
**In GNOME on Wayland**
VLC displays menus (XWayland)
Google Chrome displays menus (XWayland)
Gnome Terminal does **NOT** display menus (Wayland)

**In Gnome on X11**
VLC Displays menu (native X)
Google Chrome displays menus (native X)
Gnome terminal displays menus (Native X)
Nautilus DOES NOT display menus (nothing exported to DBus, but this is different)

**Comment by lestcape** [comment] 2017-05-09 02:49
I will be pretty honest, I have no idea, i don't have Wayland and i don't know anything of it. Maybe some one can help us with a pointer to the right direction.

**Comment by lestcape** [comment] 2017-05-30 19:32
Please see this discussion: https://bugzilla.gnome.org/show_bug.cgi?id=775061

I get the dbus menu from a windows property like hide-titlebar-when-maximized and is not supported on a Wayland session. All of this properties was removed from mutter in a Wayland session. It's really possible implement all this feature on a Wayland session, but gnome developers don't want to do that. 

They know pretty well what we need more than what we think we need and they are deciding this for us. Listen to him we don't need that, so **not global menu on Wayland**.

This is in the hands of gnome developers or could be in our hands if we fork mutter.

**Comment by lestcape** [comment] 2017-05-30 22:11
The dBus Menu are contemplate as freedesktop.org properties for a Wayland compositors, so probably the Bus can be retried some how.
Usefull links:
https://bugzilla.gnome.org/show_bug.cgi?id=wayland
https://git.gnome.org/browse/gtk+//commit/?id=d34335e51c98efebe010bd4a202fe2a4b2fb7d06&utm_source=anzwix
https://bugzilla.gnome.org/show_bug.cgi?id=707129
http://blog.broulik.de/2016/10/global-menus-returning/
https://mail.gnome.org/archives/commits-list/2017-January/msg05434.html
https://bugzilla.gnome.org/show_bug.cgi?id=773686

**Comment by lestcape** [comment] 2017-06-23 00:01
Hi @rilian-la-te Can you help in this? I see that on Wayland there are not such thing like window xid. I have a version of the extension where i split different the behaviours inside different providers... So, i have one provider working with registrar iface and another working with the GMenuModel. I notices that Wayland application do not export the menu and also don't hide the menu bar with the unity-gtk-module of ubuntu. All is working ok on X11, so i think unity-gtk-module need something more to work under Wayland. For example, maybe it's trying to access to the xid of the windows and like are not there, is not working propertly... Have you some theory about the cause of this or how can be fixed for Wayland?

**Comment by lestcape** [comment] 2017-06-23 00:17
@rilian-la-te  Yes i see your copy of unity-gtk-module, you use the xid and the xdisplay and x11 atom properties... Jummm... To work on wayland i will need to reimplemented the whole module using wayland surfaces. a lot of work!!

**Comment by rilian-la-te** [comment] 2017-06-23 05:54
For now, you need to insert this module in compositor, and announce support of GTK wayland protocol.

**Comment by rilian-la-te** [comment] 2017-06-23 06:03
we need to announce menu properties somehow. So, we can reimplement unity-gtk-module for using Registrar (sample DBus iface, in which GTK will send info about a window). This is MenuModel proto problem (For now, it stores information in X or Wayland-Gtk-Proto properties)

AFAIK, DBusMenu proto can send a registration to Registrar without a zero knowlege about Window System. (But for made Global Menu work, we need to know active window).

How it can be acheived:
1. Implement BAMF into compositor (or another protocol, which can handle Active Window and its switching. We actually need an one property (ActiveWindow) in registrar coordinates, and signal than shows a switching on it)
2. Implement Registrar for MenuModel proto

**Comment by rilian-la-te** [comment] 2017-06-23 06:08
We cannot use Wayland-Gtk-Proto (gtk-shell), because it works only with mutter.

**Comment by lestcape** [comment] 2017-06-23 16:10
Mmmm. I agree with you, but the usage of registrar is not clear to me (i think in wayland it's a dead api). This is because how we will get the xwindow (the xid) in Wayland? In kde, they let to used the cononical regitrar iface and they get the sender and path directly from the window. So, not qt support for registrar any-more. In the another hand i have an iface for GMenuModel and GMenuModel don't used the xid... Also inside Gnome the qt application are working currently in XWayland, so we can not add support for Qt application yet.

About the active window, probably form the GdkWindow system, as is fully supported under Wayland?

**Comment by rilian-la-te** [comment] 2017-06-23 19:27
No. We can use Registrar for Wayland, it is not dead API. For MenuModel we can use similar interface to capture paths directly. 
So, one task remains - determine active window. Because in GNOME we are in compositor, we can use MetaWindow API to determine active window, and associate it with path from Registrar (by using some heuristics, or using a SurfaceID, if wayland exposes an unique SurfaceID to its childs).

**Comment by rilian-la-te** [comment] 2017-06-23 19:29
Qt already uses Registrar for its Global Menu API.

**Comment by lestcape** [comment] 2017-06-23 20:34
No is not so easy... There are not any way to identify a surface (window) in Wayland, not similar to xid. Also Registrar iface won't exist any-more, or where it is?
https://phabricator.kde.org/R108:93938d60b84df81733da7b3f697332fc76fe085b

**Comment by lestcape** [comment] 2017-06-23 21:26
As you can see they create a new Dbus protocol to register the menu:
```
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
  <interface name="org.kde.kappmenu">
    <method name="showMenu">
        <arg name="x" type="i" direction="in"/>
        <arg name="y" type="i" direction="in"/>
        <arg name="service" type="s" direction="in"/>
        <arg name="objectPath" type="o" direction="in"/>
        <arg name="actionId" type="i" direction="in"/>
    </method>
    <method name="reconfigure">
    </method>
    <signal name="reconfigured" />
    <signal name="showRequest">
        <arg name="service" type="s" direction="out"/>
        <arg name="objectPath" type="o" direction="out"/>
        <arg name="actionId" type="i" direction="out"/>
    </signal>
    <signal name="menuShown">
        <arg name="service" type="s" direction="out"/>
        <arg name="objectPath" type="o" direction="out"/>
    </signal>
    <signal name="menuHidden">
        <arg name="service" type="s" direction="out"/>
        <arg name="objectPath" type="o" direction="out"/>
    </signal>
  </interface>
</node>
```
I think if there are a solution, this need to be in concordance with the windows manager and not directly with the wayland compositor, because Wayland not provide a thing like that. I don't have any idea of how associate a Wayland surface with a menu without to have some mechanisms to identify a windows and his relate menu. So, we need to have a library with a directly communication with Wayland, that can map the windows at the session start and also associate the menu to the corresponding windows. This is something like a windows manager. We can implemented it? I think not, we need to used the current windows manager. 

Luckily, mutter seems to support menubar, but someone (unity-gtk-module), will need to set it using gtk-shell from the gtk surfaces.

**Comment by lestcape** [comment] 2017-06-24 02:21
I think will be possible, that we can make it in a better way (without any dependencies of mutter) just using the gdk backend:
gdk_wayland_window_set_dbus_properties_libgtk_only

**Comment by rilian-la-te** [comment] 2017-06-24 17:30
No, we cannot, it depends on abilitiy to determine active window. 
But AFAIK, we can use some properties to identify window by some compositor-only identifier an tell it to window after its creation. 
Gtk-Shell May be a savoir, but some WMs May not want to implement it. 

Registrar is here: 
https://github.com/KDE/plasma-workspace/blob/master/appmenu/com.canonical.AppMenu.Registrar.xml

**Comment by lestcape** [comment] 2017-06-24 21:51
Yes, i know you want a general behaviour that do not depend of a windows manager. Registrar is there for the XWayland system. XWayland handled the xid, because are X11 windows inside the Wayland compositor as a wrapper. But for pure wayland i don't see something like Surface id... The active windows is not a problem, the windows that is currently calling the realize hack of the unity-gtk-module is the active windows. You probably can used in your implementation the BAMF windows system, but i can not in gjs, so i have not any other solution than used Mutter, but what is a problem to me is make to work the unity-gtk-module. This mean find a way to set the menubar of the windows in a way that also mutter will be reported about the menu path, to then get it from the gjs side. I know this is not the best and do not resolved anything to you, but is the most easy thing to me and will resolved my problem.

If i understand how you will map the windows to his menubar and is in a way that also i will can used it i can try to do the thing in your way, because i thing id better... But is not clear to me how...

**Comment by lestcape** [comment] 2017-06-24 23:49
I think probably xdg_shell, will be finally a wayland stable protocol and the common way to share information between toolkits and the wayaland compositor. but really i don't know right now how to used it. https://phoronix.com/scan.php?page=news_item&px=Wayland-XDG-Shell-Stable-Plan

**Comment by lestcape** [comment] 2017-06-24 23:51
And read: https://github.com/KDE/plasma-workspace/commit/90de42f2976c7220469d04debe185bb854c44082

**Comment by lestcape** [comment] 2017-06-25 00:28
I suppose I will need to wait for a reversion of this:
https://github.com/carlosdelfino/GTK-plus/commit/d2385bec093a85f62a06a65208bce5617a10b9a2

**Comment by rilian-la-te** [comment] 2017-06-25 10:26
1. We have ```gdk_wayland_window_export_handle```
And we may decide to export a handle for all GTK applications, and identify it by handles.
2. We can build a registrar-like interface for interacting with handles.
3. We can associate a handle with a window inside WM.
4. And finally, we will get a menu this way. So, we only need another gtk-module for Wayland Registrar.

**Comment by lestcape** [comment] 2017-06-25 14:33
This is also an unestable api... Also the handle will exist in the GdkWindow, but not need to be implemented a way inside the WM to retrive the handled that you set outside the WM. In fact there are not way currently in mutter to associate a handle with a window.

**Comment by lestcape** [comment] 2017-06-25 15:39
@rilian-la-te How i can debug unity-gtk-module. I open a dialog inside unity-gtk-module, because this will insert a main loop to wait for the dialog to be close and this give the possibility to print things in the terminal and see the output while i execute applications from the terminal...

I will be working to find a solution here: https://github.com/lestcape/unity-gtk-module

**Comment by lestcape** [comment] 2017-06-25 16:36
Hmmm, i see the problem with my solution. We can set only one time the dbus properties of a windows... I try to set it after it was set by gtk (too bad):

https://github.com/GNOME/gtk/blob/24f9d2909393b8a2267e30d3f8b6e31d6aaee850/gdk/wayland/gdkwindow-wayland.c#L3890

**Comment by rilian-la-te** [comment] 2017-06-25 18:57
I think using this function is not good, because we cannot get properties, and we sets it to gtk-shell. But it will be normal temporary solution.

**Comment by lestcape** [comment] 2017-06-25 19:30
I now also think the same, because to apply this function the window will need to be realized, bad if we call the realized, then this value are set and then we can not set it again. The only place to call it is in the middle of the realized function, but we can not split the gtk realized in two steeps... So, I'm again in the begin without nothing... :(

**Comment by lestcape** [comment] 2017-06-25 21:48
https://bugzilla.gnome.org/show_bug.cgi?id=784188

**Comment by lestcape** [comment] 2018-01-02 20:54
**Was added initial support for Wayland.**

The code to support Wayland can be found here: https://github.com/lestcape/unity-gtk-module It's just tested on Ubuntu 16.04 and probably will not work on any other places. The change will be merged with theimplementation of @rilian-la-te of his vala-panel-appmenu (https://github.com/rilian-la-te/vala-panel-appmenu), as this package is distribute on most of linux distros. You are free to copy this implementation and port it to the place you want, but the gnome global menu will STOP to used the unity-gtk-module in favor of the fork of unity-gtk-module of @rilian-la-te, as this implementation it's more general and is supported in more linux distibutions.

**Known issues of the global menu on Wayland:**

 -   The menu dosen't not work in the gnome-terminal application, as there are not support on gnome wayland for the gtk-shell-show-menubar property of the gtk settings when we use the XSettings binding.
 -   The menu will not work for windows that are not a GtkApplicationWindow.

**Closed by lestcape** 2018-01-02 20:54 UTC
