### ISSUE TITLE
Some apps with strange behaviour

### ISSUE THREAD

**Issue by fmeloni** [lestcape/Gnome-Global-AppMenu#55] opened 2017-07-27 22:18 UTC
Fedora 26, Gnome 2.24 here. I've found that some apps have a different behaviour from any one you said we could expect: they show the menu twice, once in the application window, as usual, an also as global menu. It is as if with those applications the extension is capable of capturing all the DBUS and menu information to create the global menu but it can't hide the menu from the main window. These applications are, so far:

- Gimp
- MComix
- Crossover
- SME

With MComix happens, also, that this application has the option of hiding the menu. When you do this, after restarting the application it happens that th global menu is hidden too.

**Comment by lestcape** [comment] 2017-07-27 22:54
@fmeloni this is a duplicate of https://github.com/lestcape/Gnome-Global-AppMenu/issues/49

**Closed** 2017-07-27 22:54 UTC
