### ISSUE TITLE
Duplicated menu entries in global menu

### ISSUE THREAD

**Issue by fmeloni** [lestcape/Gnome-Global-AppMenu#56] opened 2017-07-27 22:40 UTC
There are some apps written in GTK 3 that, as usual, only have the app menu in the top bar. When running this applications with the extension turned on, a new menu entry is added and showed as global menu that duplicates the application menu. It is having twice the same menu entry, on at the side of the other.

Examples of these applications are GNOME MPV exit Lollipop.

**Comment by lestcape** [comment] 2017-07-27 23:02
I don't understand... Duplicate menu inside the global menu or inside gnome shell as a whole?

Do you mean one inside the global menu and another inside the gnome appmenu? If that the case I don't develop the gnome appmenu, so, i don't care what occurs there... I provide an option to disable the gnome appmenu in the settings of the global menu (because yes is duplicate), but i do not want to limited my extension to only show the classical menu bar just because other extension also provide the same. Also there are no reason to duplicate the icon and the label in the panel.

Is this the case you are reporting? Please if not let me to know or i will close this as invalid.

**Comment by fmeloni** [comment] 2017-07-28 14:45
I know that you don't develop the gnome appmenu, that's more than clear. The situation is that you get the gnome appmenu, as expected, and then a second menu at the side of it that is an exact copy of the gnome appmenu, except the icon is missing.

For sure this menu comes from the application, there's no other place where it could originate. But my point is that hiding the gnome appmenu is not an option, since this is a setting that affects all the applications, including the ones where the gnome appmenu has useful features and hiding it means to lose the access to them. Unity manages well to not duplicate menu entries, so maybe there is a way of checking if the menu entry is already in the gnome appmenu and then, not showing it if that's the case.

**Comment by lestcape** [comment] 2017-07-28 17:00
Duplicate of #45

**Closed by lestcape** 2017-07-28 17:00 UTC
Labels: invalid

**Comment by lestcape** [comment] 2017-07-28 17:09
I speak of my settings, not about the settings of gnome, see the picture: https://user-images.githubusercontent.com/1389572/28146563-8d50d5f2-6740-11e7-8715-b1a64007bcf0.png

**Comment by lestcape** [comment] 2017-07-28 17:36
The true is, that i don't need to disable the gnome appmenu, is gnome who need to provide a way to disable his menu without change the gtk settings appmenu. They hard-code his menu and the only real way to disable it is like you say affecting other extensions that want to used this functionality. I force to destroy the gnome appmenu and this of course could produced a lot of problem is gnome change his implementation in the future.

Anyway, non of this is a responsibility of my extension, so if you have something more to add about this. Please to speak about what can do or what can not do the gnome appmenu, the right place is in bugzilla, not here.

**Comment by lestcape** [comment] 2017-07-28 18:28
I also try to create an extension where i will want to take the control of all gnome stuff and produced a more configurable gnome desktop. Is hard to do that, you can help me if you want in this attempt or you can open an issue in the gnome side if what you want is options to changed the gnome components.

**Comment by fmeloni** [comment] 2017-07-28 20:47
Dude, I totally get your point, don't worry. I also appreciate a lot the work you are doing. If there is something I can help you with, that's testing. We can design many test scenarios and can try them every time a new version of the extension is released, giving you detailed results. If that works for you, I am in.

También hablo español perfecto, si es más fácil para nuestra comunicación.

**Comment by lestcape** [comment] 2017-07-28 21:26
Sorry if i write to much things... Will be nice have a fill-back to fix real extensions problems. This extension have a lot of problems that is true and a i want to fixed it, but i really don't want/can fixed all gnome shell problems/limitations. This is my point. You are welcome like all to help in what you want/can, the extension is also your extension. Probably you like more the global menu like me :)

**Comment by fmeloni** [comment] 2017-07-29 19:58
You already created the hype, dude. You are in the Linux news all over the world. Don't give up!

**Comment by lestcape** [comment] 2017-07-29 20:31
Ohh not, I really don't like the global menu and this is not a surrender. From the begin i just make it because i love linux in general and i'm against people that want limited linux at his own vision of how things "need to be", like gnome or canonical. Linux is for all, not for an individual company. What i can do against companies it's just an insignificant changes, but we are a lot of people making a lot of insignificant changes.

**Comment by fmeloni** [comment] 2017-07-29 23:48
Well, there you had your littler win this year, when Canonical killed Unity. But that's something that, to a certain extent, it is good to have. If there weren't certain rules, this would be pure chaos, so some sort of "this is my vision" thing is always good. What's not good is when they add the "and this is the only vision" after.

**Comment by fmeloni** [comment] 2017-07-30 00:11
Look, this is what I mean by "duplicate menu entry". It happens in Libreoffice too.

First of all, that is NOT the extension menu. I don't show it, neither the icon, because I think it is unnecesary. This is the proof:

![screenshot from 2017-07-29 20-08-06](https://user-images.githubusercontent.com/19317495/28749574-e41bccaa-7499-11e7-89e4-4301aaf64d69.png)

Then, this is the first screenshot of Libreoffice:

![1](https://user-images.githubusercontent.com/19317495/28749579-fba56fb6-7499-11e7-9f18-fbf3b5b1888b.png)


And this is the second screenshot of Libreoffice:

![2](https://user-images.githubusercontent.com/19317495/28749583-0481b48c-749a-11e7-8f31-588d400e4f2c.png)

As you can see, there is a menu entry that is an exact copy of the application menu.

**Comment by lestcape** [comment] 2017-07-30 00:13
No, i never want that unity die. In fact that is another defeat for me. What i want is make possible all things, create thing thinking on users... Unity introduced a lot of new features to the linux world, this can not be wrong... What is wrong for me is limited the desktop to only allow some features or hard-set his features to be difficult change it or not support  intentional other features, when this is just because of stupid reasons or personal reasons.

**Comment by lestcape** [comment] 2017-07-30 00:14
Set "Use the extension as a replace of Gnome AppMenu" to true and then see what happens.

**Comment by fmeloni** [comment] 2017-07-30 00:31
I get what you are saying. When I set that to true, the menu every application has is gone and there is no duplicated menu at all. My point is that works only for certain applications. There are other applications that need to have their menu active because they hold important items there and if you replace it with the extension menu, you lose them. Here you have one example:

GNOME MPV's menu and extension configuration:

![1](https://user-images.githubusercontent.com/19317495/28749657-a2211780-749c-11e7-9aab-a90737682d85.png)

Extension replacing the menu:

![2](https://user-images.githubusercontent.com/19317495/28749663-b65ec602-749c-11e7-984c-f9f052b7bfdb.png)

BAM! No more access to the preferences and keyboard shortcuts of GNOME MPV.

To close my point: replacing the application menu with the extension menu works only in the cases where the menu is duplicated. When the menu is not duplicated, you are trimming functionality off the application.

**Comment by fmeloni** [comment] 2017-07-30 00:36
My proposed solution:

1- Never show the original Gnome AppMenu
2- Make the extension application icon/name to provide a copy of the Gnome AppMenu when clicked
3- Detect if the application has another menu that repeats the Gnome AppMenu and do not show it in the global menu

**Comment by lestcape** [comment] 2017-07-30 00:38
@fmeloni in my computer, mpv have not a menu... 
The global menu is disable and see:
![captura de pantalla de 2017-07-29 19-37-46](https://user-images.githubusercontent.com/1389572/28749681-7db953dc-7495-11e7-9564-98cf69e72fcc.png)

**Comment by lestcape** [comment] 2017-07-30 00:43
1- **Never show the original Gnome AppMenu-** No, this is a user preference as you can see and have nothing to be with my extension.
2- **Make the extension application icon/name to provide a copy of the Gnome AppMenu when clicked-** not directly, because then it will work diferent depending of if there are a classical global menu or not. What was implemented is a behaviour like in unity. Exactly the same.
3- **Detect if the application has another menu that repeats the Gnome AppMenu and do not show it in the global menu-** What you mean with another menu?

**Comment by lestcape** [comment] 2017-07-30 00:50
Anyway the menu that you display with preference and more things is not a dbus menu and i don't know where you found it, i don't used mpv... I only can detected menus that will be exported over dbus if is not exported i can not do anything. Read the extension description.

**Comment by lestcape** [comment] 2017-07-30 00:54
Also i can not try to fix some thing if the menu is not displayed in unity propertly. The mpv menu is not displayed in unity. Again read the description.

**Comment by fmeloni** [comment] 2017-07-30 01:15
1- Never show the original Gnome AppMenu- No, this is a user preference as you can see and have nothing to be with my extension. **OK, agree.**
2- Make the extension application icon/name to provide a copy of the Gnome AppMenu when clicked- not directly, because then it will work diferent depending of if there are a classical global menu or not. What was implemented is a behaviour like in unity. Exactly the same. **It is not exactly the same behaviour as Unity, that's what I am trying hard to show you. In Unity, this menu is moved inside the application window and you never lose it. When using the extension and not showing the Gnome AppMenu, this menu and its functionality is completely gone. There are more applications with the same problem. There are applications like Geary, that when the extension is active the preferences menu is added to the application windows as a gear icon. But there are other applications like Gnome Dictionary or Gnome Document Viewer that when the extension is active and not showing Gnome AppMenu, the preferences menu is innaccessible, is lost. This is what needs to be taken care of and Unity does it correctly.**
3- Detect if the application has another menu that repeats the Gnome AppMenu and do not show it in the global menu- What you mean with another menu? **Well, I showed you that applications like Libreoffice add a Libreoffice menu with the same content as the Gnome AppMenu. Again, Unity does not show this Libreoffice menu, never ever. So in this case, the extension is not behaving exactly like Unity. Unity manages to find out that this menu is a copy of the Gnome AppMenu and hides it.**

**Comment by lestcape** [comment] 2017-07-30 01:21
![captura de pantalla de 2017-07-29 20-12-41](https://user-images.githubusercontent.com/1389572/28749857-ea3a149c-749a-11e7-8da4-52557f7f9b0d.png)

I'm who try to show you that if this not work correctly is not for a design decision. Is because you have a problem in your instalation, the global menu have a problem with some of your settings or your software in general or something, but not because a design issue.

The red line is the app name and the icon of the global menu.
The blue line is the appmenu that is include inside the global menu extension.
The green line is the appmenu of the gnome.
There are in dis case not menubar.

**Comment by lestcape** [comment] 2017-07-30 01:24
This is what is show when you enable the setting option:
![captura de pantalla de 2017-07-29 20-22-27](https://user-images.githubusercontent.com/1389572/28749876-b5425f78-749b-11e7-8a84-89f96dd49ebb.png)

As you can see the gnome copy of the appmenu disappear (the green), but not the blue one that is the copy of the appmenu that the global menu have.

**Comment by lestcape** [comment] 2017-07-30 01:34
If you can not reproduced this behavior, there are a bug some where, not a wrong design decision.

**Comment by lestcape** [comment] 2017-07-30 01:46
Then, this is the first screenshot of Libreoffice:
![captura de pantalla de 2017-07-29 20-44-49](https://user-images.githubusercontent.com/1389572/28749966-e116f408-749e-11e7-8535-15139199d1b1.png)
And this is the second screenshot of Libreoffice (with the settings enable):
![captura de pantalla de 2017-07-29 20-44-22](https://user-images.githubusercontent.com/1389572/28749969-fa49100a-749e-11e7-94bb-24728d482096.png)

**Comment by lestcape** [comment] 2017-07-30 01:50
And this is what occurs in unity:
![Uploading Captura de pantalla de 2017-07-29 20-47-58.png…]()

As you can see the menu is not directly over the application name is a new item at the left side of the application name, like occurs in the global menu extension.

**Comment by lestcape** [comment] 2017-07-30 01:56
We agree now?

**Comment by lestcape** [comment] 2017-07-30 05:11
An also see: cannonical modify a lot of application with a patch that only will be apply on untity desktop, This is the way of how they detected all things correctly, because they modify the application to do what they need. I can not do that, of course... I'm not a distribution like ubuntu and i have not the time to do all this... What i do, is detected if there are or not a menu and set it, not more than that and i will not do more than that and i can not do more than that. Again if you have problems with gnome application, the right place is https://bugzilla.gnome.org/, not here. I'm not a developer of the gnome applications.

If you don't believe that all this is "detecting" with overriding the application, well don't believe me believe in what it say one of the ubuntu desktop team: https://medium.com/@iain.lane/welcome-16c91c0a71fb

**Comment by lestcape** [comment] 2017-07-30 05:31
An example: evince (Gnome Document Viewer) In evince by default (without cannonical patches) if the gtk menubar environment variable is set the application export only the menu bar and not the appmenu. If is not set the menubar, but it set the appmenu then it export the appmenu only. There are not way o export both things at the same time by default. The way is hack the application and modify it to be possible export both menu at the same time a thing that was make by cannonical to work only inside unity. So, forge your dreams this is the reality. The designing of the global menu is exactly the same of unity, the application running on gnome won't work with canonical patches, so don't wait then to be the same, because is not possible.

**Comment by fmeloni** [comment] 2017-07-30 18:12
A ver,  vamos a hablar en español porque me parece que en inglés no nos estamos entendiendo.

Yo entiendo perfectamente todo lo que estás explicando: que no sos Canonical, que ellos parcharon cosas, que no te vas a meter con otras cosas y demás. También entiendo los settings de la extensión y cómo funciona el unity-gtk-module.

Yo tengo la impresión de un par de cosas:

1) No estás teniendo en cuenta parámetros importantes a la hora del desarrollo. Tú mismo ya has dicho que no tienes dos monitores o que tu implementación de Gnome no corre sobre Wayland. Yo estoy trabajando con Fedora 26 y Gnome 3.24. Bleeding edge, como le dicen en inglés. ¿No se te ocurrió pensar que existe la probabilidad de que unity-gtk esté teniendo problemas con Wayñand y/o las últimas versiones de Gnome antes de decir qué hay un problema con mi instalación?
2) Las propuestas que te estoy haciendo respecto del funcionamiento pasan por emular el resultado final del global menu en Unity, nada más. Si tus limitaciones son quedarte con lo básico de un módulo que muy probablemente se discontinúe cuando Unity esté oficialmente muerto, está extension va a estar DOA. ¿No te interesa, realmente, llevarla un paso más allá y hacer algo realmente funcional para Gnome?

**Comment by lestcape** [comment] 2017-07-31 15:02
Ok, en español entonces.
1- "_No estás teniendo en cuenta parámetros importantes a la hora del desarrollo._" ¿Importantes para ti? No esos parámtros importantes para ti, no los estoy teniendo en cuenta, porque Gnome no soporta ni varias instancias de una extensión, ni soporta tener más de un panel. Te repito que mi intención aquí no es parchar gnome, ni lo voy a hacer en esta extesión, aunque si lo estoy haciedo en otra extensión: https://github.com/lestcape/Classic-Gnome pero esto debería de ser desarrollado por gnome, no por mi...

"_¿No se te ocurrió pensar que existe la probabilidad de que unity-gtk esté teniendo problemas con Wayñand y/o las últimas versiones de Gnome antes de decir qué hay un problema con mi instalación?_ ", Por supuesto que no, la extensión no soporta wayland, solo funciona en x11, si la usas en wayland es muy tu problema, porque yo ya he dicho que no funciona en wayland. Si te das cuenta, si he intentado hacerla funcionar en wayland, el hilo de Wayland está abierto, lo pudes consultar. La única forma de hacerla funcionar en wayland está parchada por gnome para que solo la usen ellos, ¿que bonito verdad? Y si hay un problema con tu instalación indistintamente del compositor que usas, pero además de esto usar la extensión en wayland es un problema de tu instalación, porque la extensión no soporta wayland.

Tu mismo estas diciendo que ya yo he dicho que la extensión no funciona en Wayland, ¿qué haces reportando cosas sobre wayland entonces?

2- A mi no me interesa llevar nada a donde tu quieras que valla, la voy a llevar a donde yo quiera que valla, mientras sea yo quien la desarrolle. ¿Te he pedido ayuda acaso para llevarla a donde tu quieres? A quien le interese algo es libre de desarrollarlo. Si está bien implementado es últi y funciona lo voy a mezclar, de otra forma no.

En resumen, que a mi me interesan muchas cosas, pero reportar bugs que yo se que existen y que no tengo forma de resolver, no me ayuda en nada, solo me entretiene un rato tratandote de explicar que eso no lo puedo resolver yo. Cuando tengas una forma de resolverlo hablamos. Yo hice una aplicación que es puramente gjs javascript. Nada más y la hice pese a que no me gusta ni me interesa, para los que si les gusta y les interesa. Incluso he tratado de que unity-gtk-module funcione en Wayland, pero simplemente no se puede. Se va a poder aparentemente cuando libren el protocolo xdg-shell, que no es estable todavía. En las manos de gnome está la solución, no en las mias. si gnome no quiere que le modifiquen los menus de las aplicaciones y bloquea la unica forma que hay de hacerlo, ¿dime que puedo hacer yo?

**Comment by lestcape** [comment] 2017-07-31 16:06
En resumen, yo no pido donaciones, porque NO quiero que alguien decida por mi en que trabajar ni cuando hacerlo, ni como hacerlo. Como nadie me paga no le debo nada a nadie, pero tampoco le impongo a nadie que use lo que hago. Me fui de cinamon con una cantidad de cosas ya realizadas vastante conciderble, solo porque trataron de imponerme cosas y manejarme. Disculpa eso no lo vas a lograr tu. Aquí lo que yo hago y en como lo hago, lo decido yo, nadie más.

Indistintamente a esto si tomo la opinión de todos porque lo que hago no es para mi, pero es tomar la opinión valorarla y decidir yo, si me parece que puedo hacerlo, si quiero hacerlo ect. De igual forma tampoco estoy en contra de incluir el trabajo de otros, mientras no dañe el mio ni realmente lo tenga que hacer yo. Mi tiempo lo decido yo, mientras no me lo pague alguien. 

Si tu quieres ponerme a modificar aplicaciones una por una o a contactar desarrolladores, molestarlos y además proponerles paraches para sus aplicaciones que ellos no quieren tener, ese trabajo vas a tener que pagarmelo o hacerlo tu. Si tu quieres que hacke gnome (algo que concidero no debo hacer) para que las cosas funcionen como tu crees que deben de funcionar pese a todo y en contra de mi voluntad, ese trabajo vas a tener que pagarmelo o hacerlo tu. YO NO RECIVO DONACIONES Y POR TANTO TAMPOCO IMPOSICIONES. Si te queda claro esto y todavía bajo esos terminos quieres colaborar, eres libre de hacerlo, gracias por tu ayuda en nombre de los usarios, en el mio propio, no tengo nada que agradecerte, no me interesa el global menu.
