### ISSUE TITLE
Allow user to choose which gtk-module to use

### ISSUE THREAD

**Issue by rilian-la-te** [lestcape/Gnome-Global-AppMenu#74] opened 2018-01-08 14:30 UTC
For now it is forced to unity-gtk-module. But we have 2 similar modules)

**Comment by lestcape** [comment] 2018-01-08 15:14
I don't think i can make it in that way. What you think if with a default preference we enable one or the other.

In ubuntu i think for now need to be the unity-gtk-module the first choose and appmenu-gtk-module the second in any other distro specially in fedora the opposite.

The idea of the preference it's enable the first that it's installed. I think searching for a file of the package probably...

What you think about it?

The problem it's that change the backend required a session restart, so i can not provide something dynamically. Also i have an option that set the unity-gtk-module for the global and the user profile, that also required root, so dynamically is not possible.

**Comment by rilian-la-te** [comment] 2018-01-08 15:20
It is good, but for now it forces me to change appmenu to unity, which is not good.
And does not work before restart (and such change).

> The problem it's that change the backend required a session restart, so i can not provide something dynamically. Also i have an option that set the unity-gtk-module for the global and the user profile, that also required root, so dynamically is not possible.

This is a problem, for sure.
I am testing Wayland now, so, forced to use your extension. And run to a couple of issues:

1. Forces me to change to unity-gtk-module (In my ArchLinux I do not have one).
2. Cannot register QtCreator (registrar getWindows shows nothing, but QtCreator menu is captured)
3. File-roller is not showing menubar (but it is its issue then)

Strangely, DeadBeef and example working with my latest code (not published yet, because it is not ready)

**Comment by lestcape** [comment] 2018-01-08 15:44
1-Really not if you enable all manually in your session, but well is better that it will work out the box.
2- My registrar is not implemented fully, just what i use. So, not try to call directly the dbus functions.
3- File-roller is working on ubuntu, if you do something for your implementation in vala to be working outside ubuntu and this can be ported to the appmenu-gtk-module this will be the only way of how i can resolved it, because i can not modify anything from javascript. This is the case, you do something special?

**Comment by rilian-la-te** [comment] 2018-01-08 15:47
No, file-roller on Wayland just not export a menu.
But on X all exported. No gtk-module required.

About registrar - I will commit you a screen of bug shortly (sorry, I am working in MATE, not GNOME).

About 1 - can you do your module requirement as adding, but not as replacing?

**Comment by rilian-la-te** [comment] 2018-01-08 15:52
Screenshots.
File-roller incorrect:
![screenshot from 2018-01-08 18-50-00](https://user-images.githubusercontent.com/1329638/34678689-ec76be24-f4a4-11e7-8639-d3f5d8bd1eaa.png)
File-roller correct:
![scr1](https://user-images.githubusercontent.com/1329638/34678711-fad971be-f4a4-11e7-8c2c-4bf949eb316e.png)
QtCreator incorrect:
![screenshot from 2018-01-08 18-50-45](https://user-images.githubusercontent.com/1329638/34678726-03418418-f4a5-11e7-8a5d-49b4beeb4751.png)

With this error:
```
 qtcreator
Gtk-Message: Failed to load module "unity-gtk-module"
Failed to unregister window menu, reason: org.freedesktop.DBus.Error.NoReply ("Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.")
```
QtCreator correct:
![scr2](https://user-images.githubusercontent.com/1329638/34678761-1cb26070-f4a5-11e7-907e-eff1c4a1f9bf.png)

**Comment by lestcape** [comment] 2018-01-09 03:45
I have not time now, as i'm working on my job all day and also I have to renew my Mexican residence permit this week. The vacation finished for me :(

**Comment by rilian-la-te** [comment] 2018-01-09 04:41
Ok, sorry then.

**Comment by lestcape** [comment] 2018-01-10 01:31
This is Qt creator on gnome wayland (on ubuntu) with the version of unity-gtk-module, that i have:
![captura de pantalla de 2018-01-09 19-28-18](https://user-images.githubusercontent.com/1389572/34751629-527451ea-f573-11e7-9647-8ef4126a3789.png)

This is file-roller on gnome wayland (on ubuntu) with the version of unity-gtk-module, that i have:
![captura de pantalla de 2018-01-09 19-29-14](https://user-images.githubusercontent.com/1389572/34751658-81ddb8c2-f573-11e7-9913-8cf146c0ecfb.png)

**Comment by lestcape** [comment] 2018-01-10 01:33
I don't underestand what you are testing then, you are testing this extension or the appmenu-gtk-module or what? Like you this the Gnome-Global-Appmenu and you say mate, i don't know what think.

**Comment by rilian-la-te** [comment] 2018-01-10 05:55
For Qtcreator it is extension, because unity-gtk-module have nothing to do with it.

**Comment by rilian-la-te** [comment] 2018-01-10 05:58
About QtCreator and Idea - for me extension cannot use it.

My daily desktop is MATE, but I installed GNOME 3.26 just to test gtk-module. Gtk-module us working Ok both versions, but extension has some problems.
About file-roller - this thing have patch in Ubuntu to always show a menubar.

**Comment by lestcape** [comment] 2018-01-10 06:42
Yes, i know file-roller have a patch, but in vala-panel and outside ubuntu you fix it some how? In ubuntu, in my machine, it is working. So, i can not reproduce the problem. QtCreator is working also for me, so i can not reproduce also that problem. I have not tested recently Idea...

GNOME Shell 3.20.4 So, the extension won't work of with GNOME 3.26? I need to test it i suppose...

**Comment by rilian-la-te** [comment] 2018-01-10 09:41
I think this is not ok with Qt menus with 3.26. 
No, outside gnome-shell file-roller works out of box. 
I will try to replicate Ubuntu file-roller patch with appmenu-gtk-module.

**Comment by lestcape** [comment] 2018-01-10 18:11
> I think this is not ok with Qt menus with 3.26

For the description of the problem that you provide, i think i can not do anything. QTCreator use a package that i don't create or handled yet. In javascript i can not resolved any internal error of the application, but i will see if i can reproduce the problem when i will have the time.

**Comment by rilian-la-te** [comment] 2018-01-10 18:19
As stated in error, your registrar service is not replied to Qt, so, can you look to it?

**Comment by lestcape** [comment] 2018-01-10 18:42
The Dbus that i can used it's a fictitious one, i can not talk directly with Dbus, but instead with a gnome-shell implementation as a proxy. Something like that occurs to me using the firefox a thunderbird implementation. I force the gnome implementation to return an empty value. If it's that, probably Qt dosen't not like the return that i forced. I need to see what i can do.

**Comment by lestcape** [comment] 2018-01-10 18:50
Is this: https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/indicatorAppMenuWatcher.js#L414

**Comment by rilian-la-te** [comment] 2018-01-10 18:51
Maybe.

**Comment by lestcape** [comment] 2018-01-10 19:18
This is not the equivalent of this https://github.com/rilian-la-te/vala-panel-appmenu/issues/40 ?

**Comment by rilian-la-te** [comment] 2018-01-10 19:32
No, it is another bug( It hangs a startup before timeout expires, and then ends without a menu and with
```Failed to unregister window menu, reason: org.freedesktop.DBus.Error.NoReply ("Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.")```

**Comment by lestcape** [comment] 2018-01-10 19:38
Well is the same message that you post here: https://github.com/lestcape/Gnome-Global-AppMenu/issues/74#issuecomment-356005620

`Failed to unregister window menu, reason: org.freedesktop.DBus.Error.NoReply ("Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.")`

Same error, probably different causes.

**Comment by Userwithaname** [comment] 2018-03-22 12:33
Would it be possible to fallback to the default menus if it fails to initialize? I'm seeing this error when starting any Qt-based app.

**Comment by lestcape** [comment] 2018-03-22 13:53
@Userwithaname I'm not implemented anything to support appmenu yet, so fallback from where?

**Comment by Userwithaname** [comment] 2018-03-23 11:11
@lestcape Basically, when global menu fails, don't hide the default one.

**Comment by rilian-la-te** [comment] 2018-03-23 12:58
This is Qt issue, not gtk-module or @lestcape one, AFAIK.

**Comment by lestcape** [comment] 2018-04-30 03:45
@rilian-la-te a good way to find the Gtk module path???

The idea that i have is this:

Te extension will be loaded **unity-gtk-module** if is installed but, is not installed **appmenu-gtk-module** otherwise the extension will take the assumption that user will want to install **appmenu-gtk-module** and will used that.

The problem is locate what module is installed on run-time to be possible then acting in concordance.

One idea is used the Gtk.rc_get_module_dir (https://people.gnome.org/~gcampagna/docs/Gtk-3.0/Gtk.rc_get_module_dir.html), with in ubuntu is: /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules 

Then the parent of this path twice is /usr/lib/x86_64-linux-gnu/gtk-3.0 and modules are locate in a children "modules" folder of this location. 

But, this is always true on all distros? Have you a better idea?

**Comment by rilian-la-te** [comment] 2018-04-30 04:44
I will look for it and then answer)

**Comment by rilian-la-te** [comment] 2018-05-03 07:38
1. ```Gtk.rc_get_module_dir()``` is deprecated, but can be used.
2. As docs says, ```GTK_PATH.  Specifies a list of directories to search when GTK+ is looking for dynamically loaded objects such as the modules specified by GTK_MODULES, theme engines, input method modules, file system backends and print backends. If the path to the dynamically loaded object is given as an absolute path name, then GTK+ loads it directly. Otherwise, GTK+ goes in turn through the directories in GTK_PATH, followed by the directory .gtk-3.0 in the user's home directory, followed by the system default directory, which is libdir/gtk-3.0/modules****```
So, we need to replicate its behaviour to search for gtk module.

**Comment by lestcape** [comment] 2018-05-03 07:43
@rilian-la-te GTK_PATH is supposed to be an environment variable, but is not one of my environments 
variables. Probably if will be set  by gtk when the gtk init occurs in a launch context of a gtk app? If this is correct, don' t help me, because I try to find the GTK_PATH, outside a gtk context.

**Comment by lestcape** [comment] 2018-05-03 07:46
The first i do was write **env** inside the terminal to find a good environment variable... I found nothing.

**Comment by rilian-la-te** [comment] 2018-05-03 08:14
We do not need a GTK_PATH, we need an order to search.

1. look to GTK_PATH
2. look to ```~/.gtk-3.0```
3. look to ```${libdir}/gtk-3.0/modules```
(```${libdir}``` is by default /usr/lib, but on deb-based it is /usr/lib/${arch}, like /usr/lib//usr/lib/x86_64-linux-gnu)

**Comment by lestcape** [comment] 2018-05-03 08:27
Thanks a lot... I will try to find a way to use the ldconfig from code, to not need to execute a command line.

**Comment by lestcape** [comment] 2018-05-03 17:01
Well is now possible use both modules.... I need to update the appmenu-gtk-module from your source and test it, because in wayland the version that it is in the ubuntu repo, won't work ok...

Closing this as i really long...

**Closed by lestcape** 2018-05-03 17:01 UTC

**Comment by rilian-la-te** [comment] 2018-05-03 17:25
OK, please test it and report bugs, I will try to fix it.

**Comment by lestcape** [comment] 2018-05-03 17:34
I have Ubuntu 18.04 in my home only, not in my work... When i have the time, i will test it in wayland... Wayland is difficult to test as it don't allow to restart the shell and i need to discard my own errors first.
