### ISSUE TITLE
Will it work with Fedora 27 (Gnome) ?

### ISSUE THREAD

**Issue by d3sign3r** [lestcape/Gnome-Global-AppMenu#77] opened 2018-01-21 17:23 UTC
Its a question as u can see and not an issue but i would love to install it on my Fedora 27 Gnome workstation. Will it work ?

**Comment by lestcape** [comment] 2018-01-21 22:13
This extension it's working, but probably yet with some issues, this is sure a true.

**Short answer:** I don't know. I don't use Fedora.
**Long answer:** To help you to understand some important things and find a cause of a failure.

Like this is an extension and nothing else than a shell extension, this code depend only to the shell code and not to any other thing. Like is running inside the shell and the shell is common on all distributions, a failure that you probably will notice could not be an extension failure at all.

**What commons issues you can notice? (This cover just the most commons issues, not all)**

**1-** Most annoying issues are because the gnome architecture have only one thread where also the compositor is working, but well, this is not a problem of the extension it self. If you notice this please `fire a bug against the Gnome Shell Architecture instead`, not here.

You can detected this type of problem when you install the extension, because you can see how it can be slowly for some applications or also you can notice some time a shell freezes (specially when some application initialized with a big menu). This is because it's what you see, but is not because the extension it self. The cause it's that the extension is running inside the same thread where the compositor is running. A big menu will demand a big CPU usage and the CPU it's also used a lot by the compositor when the application init (to create and composite the application windows). So, both tasks required a lot of CPU usage for only one core of your processor and then you probably can notice the freeze.

**2-** If you notice the extension is not integrate perfectly with Gnome yet, this is an extension problem and please fire a bug here if you notice that.

**3-** The extension not display an specific menu, `but this menu is working perfectly on Unity desktop` and you are using the extension in an X11 Gnome desktop, most probably it's that it will be an extension problem, so fire bug here.

**4-** If the extension is not working at all the problem could be in several places.

This extension for now only read the Dbus windows attributes that the Mutter WM provide (for Gtk applications) or the Dbus windows attributes that the windows (for Qt windows) itself provide, directly to the extension. If this DBus attributes are not provided to the extension, the extension can not construct the shell menu (there are not way to create a menu without information). So, in that case the problem is outside the extension and the solution is also outside the extension then.

If you notice this on Wayland fire a bug to the unity-gtk-module **of your distro**, not here. Waverer is bug outside this extension code it's not a thing i can resolved. I proved here:
https://github.com/lestcape/unity-gtk-module

This can be resolved, but it's not in my hands resolved this for all linux distributions.

If you notice a problem on Qt applications fire a bug against Qt, if also the problem occurs on Qt5 also fire a bugs against the appmenu-qt5 package of your distribution.

In general, I can not resolved an specific distribution problem with a package that was not create or added by me to this distro.

I hope this will help you.
Regards.

**Comment by rilian-la-te** [comment] 2018-01-21 22:36
For gtk-module, you can also fill a bug for me in https://github.com/rilian-la-te/vala-panel-appmenu and label it [gtk-module].

**Comment by lestcape** [comment] 2018-01-21 22:42
@rilian-la-te Sorry, i have not find the time yet to make it a true.

It will be in that way when i have a time to add support to your package, but it's not yet a thing that i do. It will be a thing that i want to do, i will do that from sure. When i add support to your package, i think a bug can be share with both we will observed both repositories and contribute to be working together. Thats my intention from sure. This will simplify a lot of the problems from the users.

**Comment by rilian-la-te** [comment] 2018-01-21 23:05
@lestcape so far, your extension is working with my module)

**Comment by lestcape** [comment] 2018-01-21 23:56
Ups, you tell me that you need to change the appmenu name to unity to be working not? https://github.com/lestcape/Gnome-Global-AppMenu/issues/74#issuecomment-355995303

If user need to do that i can not considered it ready...

**Comment by rilian-la-te** [comment] 2018-01-22 01:54
Ok.

**Comment by lestcape** [comment] 2018-05-03 16:53
@d3sign3r it will work better in fedora now using the appmenu-gtk-module and you can report issues here or in the @rilian-la-te source.

**Closed by lestcape** 2018-05-03 16:53 UTC
Labels: question

**Comment by lestcape** [comment] 2018-05-06 12:42
Is using the appmenu-gtk-module if is installed. So need to work in fedora if you install this module instead of unity-gtk-module.
