### ISSUE TITLE
Menus extremely slow with big apps, like Gimp or Inkscape

### ISSUE THREAD

**Issue by sziberov** [lestcape/Gnome-Global-AppMenu#59] opened 2017-08-13 14:35 UTC
When opening menu I need to wait a few seconds for it to open and load, then it's became usable and I can hover items without lags. The same for submenus.

My notebook configuration:
Processor: Intel® Celeron(R) CPU B830 @ 1.80GHz × 2 
Video: Intel® Sandybridge Mobile x86/MMX/SSE2 (Intel HD Graphics (Without numbers))
Ram: 8GB
OS: Ubuntu 17.04 32-bit

**Comment by lestcape** [comment] 2017-08-14 01:41
Gnome shell have the windows composition and the ui in the same thread (that is a wrong desing in my opinion of gnome shell). The windows composition have more priority that the ui, as you can understand. If i can steel cpu (really i can not) from the only thread then the window composition will be slow. When you open a new window, both things occurs at the same time and then there are not way to be occurs faster. In Wayland this problem can be see much more ease, please see, but it the same:

https://bugzilla.gnome.org/show_bug.cgi?id=745032

**Comment by sziberov** [comment] 2017-08-14 01:58
So this is a problem of video server (or DE, don't fully understood) itself and it can be fixed only be Gnome devs?

**Comment by lestcape** [comment] 2017-08-14 02:13
The performance always is relate with all things, not just one. The main problem, can only be fixed by the gnome devs and they know about that.

What it's in my hands is create a work-around to not load all menu at window initialization (the menu initialization) and then load it after the windows finished the composition. 

Anyway what it's in my hands is create a workaround, as you can see the menu is not to much slow after, because is optimized as possible to not repeat task several times. The gnome shell appmenu that i added to the classic global menu is not optimized and is loaded several times, but it also not optimized in gnome shell, as is really a short menu. Can be optimized and we can gain some cpu clock there.

But really, do not wait for a big performance improved for the thing that are in my side, all is pretty well optimized in general. Just there are details that can be improved.

**Comment by sziberov** [comment] 2017-08-14 02:20
@letscape Okay, thanks for explaining things, and some help in future! :)

**Comment by lestcape** [comment] 2017-08-14 02:44
Not, thanks to you to take the time to report this. As a currently work-around: you could gain some time if you don't show the icons. The option is located at the end of the global menu.

**Comment by lestcape** [comment] 2017-12-23 06:26
Now we are checking if the application is busy first, then this need to work a little better now: https://github.com/lestcape/Gnome-Global-AppMenu/commit/1eb8444c2279d48fe1368590424d1bc480e7a55d

The problem is not solved because is not in my side, is in the gnome side, but something is better than nothing.

**Comment by dimztimz** [comment] 2018-05-07 22:47
I was wondering, instead of manually drawing all the menus from the javascript code, would it be possible to reuse vala-appmenu-panel and let the panel draw the menus.

That project is written in compiled language (vala, c) and does not have these performanse problems.

Basically from the javascript you just put the vala panel in the gnome shell and that is it.

Is this possible?

**Comment by lestcape** [comment] 2018-05-07 23:28
@dimztimz it's possible use the appmenu-gtk-module as this package is inside the vala-appmenu-panel  project. But well, currently is the preferred option already. About to set the vala-appmenu-panel is not just easy. The shell is fully building with clutter and not gtk. You can not easy wrap a gtk object inside a clutter actor also form a different language as you need to have a support of the shell itself if you want to do a thing like that.

Gtk4 will have fully support to render an scene graph directly inside Gtk instead of need to used Clutter to do that. Gtk4 is prepared then to support a render from an OpenGL and Vulkan backed with mean 3D support a thing that Clutter already have and is the reason of the usage inside the shell.

But anyway regardless of the Gtk4 support for an scene graph, the shell itself need to used gtk (gtk4) to render his components instead of clutter, with is not supported already.

Not less important is the fact that javascript or clutter are not the cause of the gnome shell lag, and it will not be change if you used Gtk instead of clutter, because in first place Clutter is less heavy than gtk, so is working more faster. The reason of the lag is the fact that inside gnome shell all is working in the same thread, with mean not matter what language or toolkit you used, you will have a big lag!!! 

For another hands, the difference between Vala and javascript is less than some miliseconds, and this is something that you are not able to detect so easy.

So, what is more needed is a change inside the gnome architecture at the level of how the components interact and spilt all this interaction in different well thinking and implemented close process.

**Comment by lestcape** [comment] 2018-05-09 08:59
For who want to see this: https://www.youtube.com/watch?v=FhNQIxFSewY
I will shared the asynchronous version soon.

**Comment by lestcape** [comment] 2018-05-10 00:43
Who want to test it:

1- Remove the comment (character at the begin //) of the line:
`//Mainloop.idle_add(Lang.bind(this, this._createChildrens, shellItem));`
https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/configurableMenus.js#L9032
2- Add a comment (add the character  // at the begin of the line) inside the next line:
`this._createChildrens(shellItem);`
https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/configurableMenus.js#L9033
3- Restart the shell.

It have some little problems in my test yet that why is not changed yet...

**Comment by lestcape** [comment] 2018-05-12 05:01
Apparently the ubuntu developers are taking part on the shell performance, whatever it is they can do, is for sure that the shell performance will be improved a lot:
https://trello.com/c/Q6JYXPPs/67-gnome-shell-visibly-stutters
Some specific issues are pretty related with facts that can improved the performance of rendering of the menu, for that reasons this fixes will also impact in this extension in a very visible way in the future.

**Comment by lestcape** [comment] 2018-06-05 06:21
This error was migrated to gitlab, as the development of this extension, will no longer be in github from the recently acquisition from the Microsoft company of the github website. Please to continued following it you can subscribed in this thread:
https://gitlab.com/lestcape/Gnome-Global-AppMenu/issues/59

**Closed by lestcape** 2018-06-05 06:21 UTC
Labels: bug, external bug

**Comment by sziberov** [comment] 2018-06-05 14:37
@lestcape 
![screenshot_244](https://user-images.githubusercontent.com/7362968/40982917-218a714e-68e7-11e8-98af-203fa350c30f.png)

**Comment by rilian-la-te** [comment] 2018-06-05 15:14
@lestcape please, open your repos on GitLab. It is private by default.

**Comment by lestcape** [comment] 2018-06-06 01:20
Ups... thanks...

**Comment by lestcape** [comment] 2018-06-06 01:50
done...
